use_frameworks!
platform :ios, '9.0'

target 'TabBarPageController_Example' do
  pod 'TabBarPageController', :path => '../'

  target 'TabBarPageController_Tests' do
    inherit! :search_paths
  end
end
