name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme TabBarPageController -destination "platform=iOS Simulator,OS=latest,name=iPhone 13" -disableAutomaticPackageResolution
    - name: Run tests
      run: xcodebuild test -scheme TabBarPageController -destination "platform=iOS Simulator,OS=latest,name=iPhone 13" -disableAutomaticPackageResolution
